---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_comment_tree_service }}"
template_compose_file_name: comment-tree-service.j2
template_env_file_name: comment-tree-service-env.j2
compose_file_name: "{{ service_comment_tree_service }}.yml"
env_file_name: "{{ service_comment_tree_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_comment_tree_service }}.env"
#chart_path: "../kubernetes-deploy/comment-tree-service"

env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: content validation service

# For service
application_port: "{{ comment_tree_service_port }}"
image_name: "{{ image_comment_tree_service }}"
tag: "{{ tags_comment_tree_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_comment_tree_service }}"
reserved_memory: "{{ service_mem_reserved_comment_tree_service }}"
limited_memory: "{{ service_mem_limit_comment_tree_service }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/contentValidation/actuator/health
network_alias_name: "{{ network_alias_comment_tree_service }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_comment_tree_service }}"
force_reload: "{{ force_reload_comment_tree_service }}"

cb_comment_liveness_readiness:
  healthcheck: true
  readinessProbe:
    httpGet:
      path: /liveness
      port: 8099
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 2
  livenessProbe:
    httpGet:
      path: /liveness
      port: 8099
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 2

# For application
server_connection_timeout: 5000
tomcat_max_threads: 400
tomcat_min_spare_threads: 20
servlet_multipart_max_file_size: 100Mb
servlet_multipart_max_request_size: 100Mb

content_service_url: http://{{ network_alias_content_service }}:{{ service_content_service_port }}

infosys_lex_core_ip: http://{{ network_alias_sb_cb_ext_service }}:{{ service_sb_cb_ext_port }}
