---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_cb_ext_assessment_service }}"
template_compose_file_name: cb-ext-assessment-service.j2
template_env_file_name: cb-ext-assessment-service-env.j2
compose_file_name: "{{ service_cb_ext_assessment_service }}.yml"
env_file_name: "{{ service_cb_ext_assessment_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_cb_ext_assessment_service }}.env"
#chart_path: "../kubernetes-deploy/cb-ext-assessment-service" 
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: sb-cb-ext service

# For service
application_port: "{{ service_sb_cb_ext_port }}"
image_name: "{{ image_cb_ext_assessment_service }}"
tag: "{{ tags_cb_ext_assessment_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_cb_ext_assessment_service }}"
reserved_memory: "{{ service_mem_reserved_cb_ext_assessment_service }}"
limited_memory: "{{ service_mem_limit_cb_ext_assessment_service }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/actuator/health
network_alias_name: "{{ network_alias_cb_ext_assessment_service }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_cb_ext_assessment_service }}"
force_reload: "{{ force_reload_cb_ext_assessment_service }}"

sb_cb_ext_liveness_readiness:
  healthcheck: true
  readinessProbe:
    httpGet:
      path: /liveness
      port: 7001
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 2
  livenessProbe:
    httpGet:
      path: /liveness
      port: 7001
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 2

# For application
server_connection_timeout: 5000
tomcat_max_threads: 400
tomcat_min_spare_threads: 20
servlet_multipart_max_file_size: 100Mb
servlet_multipart_max_request_size: 100Mb
spring_data_mongodb_uri: mongodb://{{ mongodb_user }}:{{ mongodb_password | urlencode }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ mongodb_authentication_database }}
spring_data_mongodb_database: telemetry
spring_data_cassandra_bodhi_startupTimeoutInSeconds: 100


pyeval_server_ip: "{{ pyeval_server_ip }}"
pyeval_server_port: "{{ pyeval_server_port }}"
pyeval_service_name: /PyEval6/

iap_server_ip: "{{ iap_server_ip }}"
iap_server_port: "{{ iap_server_port }}"
iap_verification_service: /verify/

log_access_key: "{{ log_access_key }}"




lhub_url: "{{ var_sb_cb_ext_learning_hub_url }}"
lhub_certifaction_url: "{{ var_sb_cb_ext_learning_hub_certification_url }}"
spring_datasource_jdbc_url: jdbc:postgresql://{{ postgresql_host }}:{{ postgresql_port }}/{{ postgresql_wingspan_database }}

enable_realtime_progress: "{{ var_sb_cb_ext_enable_realtime_progress }}"

root_org: Infosys
instance_org: infy01
access_control_url: http://{{ network_alias_sb_ext_service }}:{{ service_sb_ext_port }}/accesscontrol
sb_learner_service_url: http://{{ sb_learner_service }}:{{ sb_learner_service_port }}/

wf_service_host: http://{{ network_alias_workflow_handler_service }}:{{ service_workflow_handler_port }}/

lms_service_host: http://lms-service:9000/
